[core]
workspace_base="./workspace"
persist_sandbox=false
max_iterations = 100
cache_dir = "/tmp/cache"
ssh_hostname = "localhost"
use_host_network=false

[llm.gpt-4o]
model="gpt-4o"
api_key=""
embedding_model=""

[llm.o1]
model="o1"
api_key=""
embedding_model=""

[llm.o3]
model="o3-mini"
api_key=""
embedding_model=""

[llm.gemini]
model="gemini/gemini-2.0-flash"
api_key=""
embedding_model=""

[llm.gemini-thinking]
model="gemini/gemini-2.0-flash-thinking-exp"
api_key=""
embedding_model=""
